# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.0
    ports:
      - '3306:3306'
    restart: unless-stopped
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: docker.io/bitnami/wordpress:6
    ports:
      - '80:8080'
      - '443:8443'
    restart: unless-stopped
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      - 'php_conf_data:/opt/bitnami/php/etc'
      - 'wordpress_root_data:/opt/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
  vscode:
    image: "linuxserver/code-server"
    environment:
      - PUID=1
      - PGID=0
    ports:
      - "9003:9003"
      - "8443:8443"
    restart: unless-stopped
    volumes:
      - 'wordpress_root_data:/config/workspace/wordpress'

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  wordpress_root_data:
    driver: local
  php_conf_data:
    driver: local
